name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  ci:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: site24x7_exporter
            release_name: linux-x86_64
          - os: windows-latest
            artifact_name: site24x7_exporter.exe
            release_name: windows-x86_64.exe
          - os: macos-latest
            artifact_name: site24x7_exporter
            release_name: macos-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Get CHANGELOG.md entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.CURRENT_VERSION }}
          path: ./CHANGELOG.md

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          asset_name: site24x7_exporter-${{ github.event.release.tag_name }}-${{ matrix.release_name }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
